//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HalisElektronik
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cards
    {
        public int CardsId { get; set; }
        public string Title { get; set; }
        public string Barcode { get; set; }
        public int ImgSrcId { get; set; }
        public int CategoryId { get; set; }
        public string Description { get; set; }
        public double Price { get; set; }
        public int Stock { get; set; }
    
        public virtual ImgSrc ImgSrc { get; set; }
    }
}
