//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HalisElektronik
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImgSrc
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ImgSrc()
        {
            this.Cards = new HashSet<Cards>();
        }
    
        public int ImgsrcId { get; set; }
        public string ImgSrc1 { get; set; }
        public string Title { get; set; }
        public string ImgSrc2 { get; set; }
        public string ImgSrc3 { get; set; }
        public string ImgSrc4 { get; set; }
        public string ImgSrc5 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cards> Cards { get; set; }
    }
}
